#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Vinícius Bispo e colaboradores
# Run the CI checks before publishing. Enable with bin/install-hooks.
cd "$(git rev-parse --show-toplevel)" || exit 1
./bin/lint || { echo "Ruff failed; push cancelled"; exit 1; }
./bin/test   || { echo "Tests failed; push cancelled"; exit 1; }
